// Common disposable email domains to block
const DISPOSABLE_EMAIL_DOMAINS = [
  // Popular disposable email services
  'tempmail.com',
  'temp-mail.org',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'sharklasers.com',
  'spam4.me',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.de',
  'mailinator.com',
  'maildrop.cc',
  '10minutemail.com',
  '10minutemail.net',
  'throwaway.email',
  'fakeinbox.com',
  'yopmail.com',
  'temp-mail.io',
  'getnada.com',
  'trashmail.com',
  'emailondeck.com',
  'throwawaymail.com',
  'mailnesia.com',
  'tempinbox.com',
  'dispostable.com',
  'mintemail.com',
  'mytemp.email',
  'mohmal.com',
  'emailfake.com',
  'fakemailgenerator.com',
  'mailcatch.com',
  'mailtemp.info',
  'tempsky.com',
  'getairmail.com',
  'jetable.org',
  'tmail.ws',
  'inbox.lv',
  'mvrht.net',
  'tmails.net',
  'tmpmail.org',
  'tmpmail.net',
  'mailforspam.com',
  'mailsac.com',
  'burnermail.io',
  'emailtemporanea.com',
  'crazymailing.com',
  'mailexpire.com',
  'throwam.com',
  'zetmail.com',
  '0-mail.com',
  '0815.ru',
  '0clickemail.com',
  '10mail.org',
  '20email.eu',
  '2prong.com',
  '30minutemail.com',
  '33mail.com',
  'anonymbox.com',
  'bccto.me',
  'bugmenot.com',
  'deadaddress.com',
  'despam.it',
  'disposeamail.com',
  'dodgeit.com',
  'dropmail.me',
  'dumpmail.de',
  'e4ward.com',
  'einrot.com',
  'emailsensei.com',
  'filzmail.com',
  'getonemail.com',
  'gishpuppy.com',
  'great-host.in',
  'hidemail.de',
  'incognitomail.com',
  'jetable.com',
  'kasmail.com',
  'klzlk.com',
  'link2mail.net',
  'mail-temporaire.fr',
  'mail.tm',
  'mailcatch.com',
  'maileater.com',
  'mailnull.com',
  'mailslite.com',
  'mytrashmail.com',
  'no-spam.ws',
  'nospam.ze.tc',
  'nospamfor.us',
  'nowmymail.com',
  'nwldx.com',
  'objectmail.com',
  'oneoffemail.com',
  'pookmail.com',
  'proxymail.eu',
  'putthisinyourspamdatabase.com',
  'quickinbox.com',
  'rcpt.at',
  'recode.me',
  'rtrtr.com',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'saynotospams.com',
  'selfdestructingmail.com',
  'sharklasers.com',
  'shiftmail.com',
  'slaskpost.se',
  'sneakemail.com',
  'sofort-mail.de',
  'spam.la',
  'spamavert.com',
  'spambob.com',
  'spambog.com',
  'spambox.us',
  'spamcannon.com',
  'spamcero.com',
  'spamex.com',
  'spamfree24.com',
  'spamfree24.de',
  'spamgourmet.com',
  'spamherelots.com',
  'spamhole.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamspot.com',
  'spamthis.co.uk',
  'speed.1s.fr',
  'superrito.com',
  'tagyourself.com',
  'teleworm.us',
  'tempemail.net',
  'tempinbox.co.uk',
  'tempomail.fr',
  'temporarily.de',
  'tempymail.com',
  'thankyou2010.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash2009.com',
  'trashdevil.com',
  'trashemail.de',
  'trashymail.com',
  'trbvm.com',
  'tyldd.com',
  'uggsrock.com',
  'wegwerfadresse.de',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wh4f.org',
  'whyspam.me',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'wuzup.net',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yopmail.fr',
  'yopmail.net',
  'zippymail.info',
  'zoemail.net',
];

/**
 * Validates if an email address uses a disposable email domain
 * @param email - The email address to validate
 * @returns true if the email is valid (not disposable), false if it's a disposable email
 */
export function isValidEmail(email: string): boolean {
  if (!email || typeof email !== 'string') {
    return false;
  }

  // Extract domain from email
  const emailLower = email.toLowerCase().trim();
  const atIndex = emailLower.lastIndexOf('@');

  if (atIndex === -1) {
    return false;
  }

  const domain = emailLower.substring(atIndex + 1);

  // Check if domain is in the disposable list
  return !DISPOSABLE_EMAIL_DOMAINS.includes(domain);
}

/**
 * Gets a user-friendly error message for disposable email addresses
 */
export function getDisposableEmailError(): string {
  return 'Disposable email addresses are not allowed. Please use a permanent email address.';
}
