name: Supabase Production Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://get.supabase.com/cli | sh
          export PATH="$HOME/.supabase/bin:$PATH"
